name: cx_analytics
version: "1.0.0"
config-version: 2

profile: cx_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  start_date: "2016-01-01"

models:
  cx_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      customer_experience:
        +materialized: table
        +schema: customer_experience
